src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

use App\Repository\UserRepository;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(
 * fields={"email"} ,message="cet email ets deja associe a un compte")
 * @UniqueEntity(
 * fields={"pseudo"} ,message="Ce pseudo est deja utilisé"),
 * )
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * 
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank(message="merci d'indiquer un pseudo")
     */
    private $pseudo;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Assert\NotBlank(message="merci d'indiquer le mot de passe")
     *  pattern = "^\S*(?=\S{8,})(?=\S*[a-z])(?=\S*[A-Z])(?=\S*[\d])\S*$^",
     *  message = "le mot de passe doit contteir 1 majuscule, 1 miniscule et 1 chiffre"
     */
    private $password;
/**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez indiquer votre prenom")
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez indiquer votre nom")
     */
    private $nom;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->pseudo;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->pseudo;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * Get the value of prenom
     */ 
    public function getPrenom()
    {
        return $this->prenom;
    }

    /**
     * Set the value of prenom
     *
     * @return  self
     */ 
    public function setPrenom($prenom)
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * Get the value of nom
     */ 
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set the value of nom
     *
     * @return  self
     */ 
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get the value of email
     */ 
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set the value of email
     *
     * @return  self
     */ 
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }
}

src/Controller/FrontController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

class FrontController extends AbstractController
{
    /**
     * @Route("/", name="app_front")
     */
    public function index(): Response
    {
        return $this->render('front/accueil.html.twig', [
            'controller_name' => 'FrontController',
        ]);
    }

    /**
     * 
     * @Route("/profil", name="app_profil")
     */
    public function profil(){
        
        if( $this->isGranted("ROLE_USER")){

            return $this->render('front/profil.html.twig',[
                'user' => $this->getUser()
        ]);
        }else{
            return $this->redirectToRoute("app_login");
        }

    }
}

templates/front/Inscription.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscription!{% endblock %}

{% block body %}
    <h1 class="text-center">Formulaire d'Inscription</h1>
    <div class="col-6 mx-auto text-white">
        {{ form_start(formUser) }}
            {{ form_widget(formUser)}}
            <div class = "d-flex justify-content-center">
                <button class = "btn btn-success">S'inscrire</button>
            </div>
        {{ form_end(formUser) }}
    </div>

{% endblock %}

templates/front/accueil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil | IMDb {% endblock %}

{% block body %}
<div class="col d-flex justify-content-center">
    <h1 class="text-white">Bienvenue sur</h1><span class="bg-warning border-warning rounded text-center fw-bold mx-2 " style="width: 100px ;">IMDb</span>
    
</div>
<div class="mt-5">
    {% for type, message in app.flashes %} 
            {# {{ dump(app.flashes, type, message) }}  #}
        <div class="col-6 mx-auto text-center alert alert-{{type}}">
                {{ message.0 }}
        </div>
    {% endfor %}
</div>
{% endblock %}

templates/front/connexion.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block body %}
<form method="post" class="text-white">
    {% if error %}
        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    {% if app.user %}
        <div class="mb-3" text-white>
            Vous etes deja connecté en tant que  {{ app.user.username }}, <a href="{{ path('app_logout') }}">Logout</a>
        </div>
    {% endif %}
    
    {% for type, message in app.flashes %} 
        {# {{ dump(app.flashes, type, message) }}  #}
         <div class="col-6 mx-auto text-center alert alert-{{type}}">
            {{ message.0 }}
        </div>
    {% endfor %}

    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
    <label for="inputPseudo">Pseudo</label>
    <input type="text" value="{{ last_username }}" name="pseudo" id="inputPseudo" class="form-control" autocomplete="username" required autofocus>
    <label for="inputPassword">Password</label>
    <input type="password" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required>

    <input type="hidden" name="_csrf_token"
           value="{{ csrf_token('authenticate') }}"
    >

    {#
        Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
        See https://symfony.com/doc/current/security/remember_me.html

        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" name="_remember_me"> Remember me
            </label>
        </div>
    #}

    <button class="btn btn-lg btn-primary" type="submit">
        Sign in
    </button>
</form>
{% endblock %}

templates/front/profil.html.twig
{% extends "base.html.twig" %}

{% block title %}Profil{% endblock %}

{% block body %}

<h1 class="text-center text-primary">Espace Personnel</h1>
<h2 class="text-center">Bienvenue, {{ app.user.prenom ~ " " ~ app.user.nom}}</h2>

    {% for type, message in app.flashes %} 
    {# {{ dump(app.flashes, type, message) }}  #}
        <div class="col-6 mx-auto text-center alert alert-{{type}}">
            {{ message.0 }}
        </div>
    {% endfor %}

{% endblock %}